source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rake'
gem 'sinatra'
gem 'redcarpet'
gem 'compass-core'
gem 'therubyracer'
gem 'activesupport'
gem 'evil-front-all'
gem 'rails-sass-images'
gem 'term-ansicolor'

gem 'rails-assets-shower-core'
gem 'rails-assets-shower-bright'
